### PR TITLE
Fix/load button while loading

### PR DESCRIPTION
**Pull request by JamieCrisman**
The load more button will show while loading. This turns it off while loading.

## Before
loadmorepotatoes

## After
mrpotatohead

### CODE REVIEW

**Comment by robmcguinness** [comment]
@dnoler can you review?

**Comment by dnoler** [comment]
Looks good to me.

**Comment by taylornturner** [comment]
I think it needs more potatoes.

**Comment by robmcguinness** [comment]
:sweet_potato:

**Comment by robmcguinness** [comment]
before we release i want to pull in #180

**Comment by robmcguinness** [comment]
this was missed.  @JamieCrisman or @dnoler please release when ready.

**Pull request merged**
