### PR TITLE
Added dynamic breadcrumbs

### PR DESCRIPTION
**Pull request by andrewaramsay**
Added ability for breadcrumbs to specify a level (rather than an explicit parent) to make dynamic, context-sensitive breadcrumbs.

### CODE REVIEW

**Comment by robmcguinness** [comment]
@andrewaramsay any chance I can convince you to back-port this to [feature/v2](https://github.com/Availity/availity-angular/tree/feature/v2) as well? 😸

**Comment by andrewaramsay** [comment]
I'm not finding breadcrumbs in v2 at all, does the whole directive need to be migrated, or am I just missing where it was moved to?

**Comment by robmcguinness** [comment]
I think the `v2` branch was created from `v1.9.1` so anything after has to be ported.  since the code was converted to ES6 it became difficult to merge.  If you don't have time all good but it you do it would be big help.

**Comment by andrewaramsay** [comment]
breadcrumbs originally showed up in v0.13.0, over a year ago.  It looks like it was removed in commit 9b5710230cd28bdb20ef907f416a59df94d5ac62 (remove non-core modules, add back with pull requests). And no one ever added it back to v2.  Is there some specific method and/or location I should use to add now, or should I just port it to ES6 and add it back to src/ui?

**Comment by robmcguinness** [comment]
oh my bad.  I was trying to get `v2` quickly and forgot to add back in.  basically all that is needed is is to convert the previous code to ES6 + break out the component into separate files by leverage Webpack.   A bunch of examples exist in 'v2` branch already.   A good tool for quick and dirty ES6 conversion is http://lebab.io/try-it

**Pull request merged**
