### PR TITLE
debouncer more robust

### PR DESCRIPTION
**Pull request by JamieCrisman**
Fixes issue where debouncer may be triggered even though the model hasn't been touched.

### CODE REVIEW

**Comment by ivern** [comment]
I approve of this product and/or service.

**Comment by robmcguinness** [comment]
hmm...this seems like a hack.  the event is firing...the field is $dirty at that point.

**Comment by robmcguinness** [comment]
Ok I replaced the hack with a more complex hack :)  Please review and test with IE because currently can't access IE on my Mac.

**Comment by robmcguinness** [comment]
@ivern waiting on you to verify then we can cut a release

**Pull request merged**
